package com.Mitsugaru.KarmicCache;

import org.bukkit.Chunk;
import org.bukkit.Location;
import org.bukkit.entity.Player;

public class GeoCache {
	private KarmicCache plugin;
	private String name, description, world, message, hint;
	private Location location;
	private int regionX, regionZ;

	public GeoCache(KarmicCache karmicCache) {
		plugin = karmicCache;
		name = description = world = message = hint = "";
		location = null;
		regionX = regionZ = 0;
	}

	public GeoCache(KarmicCache karmicCache, Player player) {
		// Used when a player makes a cache
		plugin = karmicCache;
		location = player.getLocation();
		world = location.getWorld().getName();
		name = "GC" + String.valueOf(KarmicCache.r.nextInt(100000));
		// TODO validate name that it does not already exist in database
		// TODO defaults for message and hint and description
		// Grab chunk
		final Chunk chunk = location.getChunk();
		// Grab region
		regionX = (int) Math.floor((double) chunk.getX() / 32);
		regionZ = (int) Math.floor((double) chunk.getZ() / 32);
	}

	public GeoCache(KarmicCache karmicCache, Location loc) {
		// Used when autogenerated
		plugin = karmicCache;
		location = loc;
		world = location.getWorld().getName();
		name = "GC" + String.valueOf(KarmicCache.r.nextInt(100000));
		// TODO validate name that it does not already exist in database
		// TODO defaults for message and hint and description
		// Grab chunk
		final Chunk chunk = location.getChunk();
		// Grab region
		regionX = (int) Math.floor((double) chunk.getX() / 32);
		regionZ = (int) Math.floor((double) chunk.getZ() / 32);
	}
	
	public GeoCache(KarmicCache karmicCache, String name, String description, String message, String hint, Location location)
	{
		plugin = karmicCache;
		this.name = name;
		this.description = description;
		this.message = message;
		this.location = location;
		world = location.getWorld().getName();
	}

	public void setMessage(String m) {
		message = m;
		// TODO save
	}

	public void setHint(String h) {
		hint = h;
		// TODO save
	}

	public Location getLocation()
	{
		return location;
	}

	public String getName()
	{
		return name;
	}
}
